apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiny-url-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: tiny-url-ingress
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tiny-url-service
            port:
              number: 30200
